# Generated by Django 4.1.5 on 2023-01-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Kitchen Food', 'Kitchen Food'), ('Petrol', 'Petrol'), ('item purchasing', 'item purchasing'), ('Necessities', 'Necessities'), ('Other', 'Other')], default='Food', max_length=200, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('amount_taken', models.BigIntegerField()),
                ('amount_used', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('desc', models.TextField(null=True)),
                ('bill', models.CharField(choices=[('Bill', 'Bill'), ('No Bill', 'No Bill')], max_length=100)),
                ('remaining', models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
