# Generated by Django 4.1.5 on 2023-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remaining',
            field=models.BooleanField(default=False),
        ),
    ]
