# Generated by Django 4.1.5 on 2023-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bill',
            field=models.BooleanField(default=False),
        ),
    ]
