# Generated by Django 6.0.7 on 2026-10-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_migrate_legacy_shantipur_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.center'),
        ),
    ]
